/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:26: UserWarning: Converting G to a CSC matrix; may take a while.
  warn("Converting G to a CSC matrix; may take a while.")
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/ecos/ecos.py:29: UserWarning: Converting A to a CSC matrix; may take a while.
  warn("Converting A to a CSC matrix; may take a while.")
pygame 2.0.1 (SDL 2.0.14, Python 3.7.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
ice_hockey_v1 pettingzoo
Load ice_hockey_v1 environment in type pettingzoo.
Env observation space: Box(0.0, 1.0, (128,), float32) action space: Discrete(18)
random seed: 91
<mars.env.wrappers.mars_wrappers.Dict2TupleWrapper object at 0x7f5f24c62b00>
DQNBase(
  (net): MLP(
    (body): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=256, bias=True)
      (5): ReLU()
      (6): Linear(in_features=256, out_features=256, bias=True)
      (7): ReLU()
      (8): Linear(in_features=256, out_features=18, bias=True)
    )
  )
)
DQNBase(
  (net): MLP(
    (body): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
      (3): ReLU()
      (4): Linear(in_features=256, out_features=256, bias=True)
      (5): ReLU()
      (6): Linear(in_features=256, out_features=256, bias=True)
      (7): ReLU()
      (8): Linear(in_features=256, out_features=18, bias=True)
    )
  )
)
Agents No. [0] (index starting from 0) are not learnable.
Traceback (most recent call last):
  File "general_exploit.py", line 49, in <module>
    launch_rollout(parser_args.env, parser_args.method, parser_args.load_id, parser_args.save_id)
  File "general_exploit.py", line 38, in launch_rollout
    model = MultiAgent(env, [trained_model, exploiter], exploitation_args)
  File "/home/zihan/research/MARS/mars/rl/agents/multiagent.py", line 74, in __init__
    meta_learner.load_model(self.agents[0], path=args.load_model_full_path)  
  File "/home/zihan/research/MARS/mars/marl/meta_learner.py", line 46, in load_model
    with open(self.model_path+'policy_checkpoints.npy', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/model/20220112_0004/pettingzoo_ice_hockey_v1_nxdo2/policy_checkpoints.npy'
